### ISSUE TITLE
Search and add a player

### ISSUE THREAD

**Issue by stevenli19203** [SachaKonskier/loldraft#1]

**Comment by stevenli19203** [comment]
I want to search an user using the user name using the search bar:
![Image](https://github.com/SachaKonskier/loldraft/assets/131662448/58c387e4-b0ef-42e9-8e3b-0db706fd2450)

if the user is found, it will be added in a card below the search component :
![Image](https://github.com/SachaKonskier/loldraft/assets/131662448/0ed0971d-a6bb-4b41-9efa-9aad6dbd839e)

if the user is not found or there is an error, show the message "We are not able to find this account": 
![Image](https://github.com/SachaKonskier/loldraft/assets/131662448/9efd4d13-6f64-4e82-8f9a-340e69baf687)

Acceptance criteria :

1. Given that I add **Garen la Bagarre#Garen** in the search bar
When I click the search button
Then the user card appears

2. Given that I add **Garen la Bagarre#Garen** in the search bar
When I click the search button
Then the error message should be shown below the search bar

**Comment by SachaKonskier** [comment]
to test this feature, you have to go to the front/circularComponent branch

I added a better behavior : 
Given that I add Karen la bagarre in the search bar
When I click on the search button
Then the error message should be shown below the search bar
And the user input is now Red

When I change the input
Then the error message is not displayed anymore
And the user input is not red anymore
